### ISSUE TITLE
OpenAIRE Research Graph Dump dataset question

### ISSUE THREAD

**Issue by AChatzigoulas** [openaire/open-innovation2020#1]
Hello,

I downloaded the metadata records about research data, dataset.gz from the OpenAIRE Research Graph Dump. Can you please provide me with more information how to parse the dataset file? 

Additionally, I would like some more information about the OpenAIRE Research Graph interoperability standards for databases.

Thank you in advance,
Alexios Chatzigoulas
a.chatzigoulas@gmail.com
Dentica

**Comment by harry-di** [comment]
Dear Alexios,

You can find information on how to consume the dumps here: 
http://develop.openaire.eu/graph-dumps.html
Let me know if this solves your parsing issues. 

I'll try and get back to you to your second question about interoperability standards by Monday.

All the best.
Harry Dimitropoulos

**Comment by AChatzigoulas** [comment]
Thank you very much for your answer.

As the deadline submission is tomorrow. I would be greatful if you could also help me with my second question.

Best regards,
Alexios Chatzigoulas

**Comment by harry-di** [comment]
Hi Alexios, 

Can you please elaborate on your second question? As I could not answer it, during the weekend I asked the other supervisors in the group and they were not sure what you were looking for. They told me that the metadata format is inspired by Datacite and Dublin Core but if you are asking for dumps you can restore on a relational database, for example, this is not possible. 

By the way, regarding accessing and analysing the OpenAIRE Research Graph data dumps you might find the following post also useful: https://subugoe.github.io/scholcomm_analytics/posts/oaire_graph_2020/

Kind regards,
Harry

**Comment by zoecournia** [comment]
Dear Harry,
I think that OpenAire is based on the CERIF interoperability, which we should use, right?

My question is: How can we use the OpenAire APIs such as the ones mentioned here: https://api.openaire.eu/ (i.e. the HTTP API and the Linked Open Data API). We cannot find a way to access them. Or should we be directly using the data dumps with the code you provide here https://subugoe.github.io/scholcomm_analytics/posts/oaire_graph_2020/ ?

Your help is really appreciated!

Best
Zoe

**Comment by harry-di** [comment]
Dear Zoe,

Indeed, the OpenAIRE model is also inspired by CERIF. You can find the description of the model here: https://doi.org/10.5281/zenodo.2643199

The HTTP API is up and running as described here: http://api.openaire.eu/api.html#pubs

http://api.openaire.eu/search/publications

As a simple DOI example to use the API:
`curl 'https://api.openaire.eu/search/publications?format=xml&model=openaire&doi=<a doi>'`

If you require more information, I think it is best if you directly email CNR, e.g., Alessia Bardi at alessia.bardi@isti.cnr.it.

Regarding the LOD, you can have a look at this page: http://lod.openaire.eu/documentation and if you want more information, you can write directly to Giorgos Alexiou: galexiou@athenarc.gr

Best,
Harry
